apiVersion: v1
data:
  kubeconfig: <cluster-credentials-a1>
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/ias/qa/eu-de-1/linkerd"
  creationTimestamp: null
  name: cluster-credentials-a1
  namespace: linkerd-multicluster
type: mirror.linkerd.io/remote-kubeconfig
---
apiVersion: v1
data:
  kubeconfig: <cluster-credentials-a1>
kind: Secret
metadata:
  annotations:
    multicluster.linkerd.io/cluster-domain: cluster.local
    multicluster.linkerd.io/trust-domain: cluster.local
    avp.kubernetes.io/path: "kv-v2/data/ias/qa/eu-de-1/linkerd"
  creationTimestamp: null
  labels:
    multicluster.linkerd.io/cluster-name: a1
  name: cluster-credentials-a1
  namespace: linkerd
type: mirror.linkerd.io/remote-kubeconfig
---
apiVersion: v1
data:
  kubeconfig: <cluster-credentials-a2>
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "kv-v2/data/ias/qa/eu-de-1/linkerd"
  creationTimestamp: null
  name: cluster-credentials-a2
  namespace: linkerd-multicluster
type: mirror.linkerd.io/remote-kubeconfig
---
apiVersion: v1
data:
  kubeconfig: <cluster-credentials-a2>
kind: Secret
metadata:
  annotations:
    multicluster.linkerd.io/cluster-domain: cluster.local
    multicluster.linkerd.io/trust-domain: cluster.local
    avp.kubernetes.io/path: "kv-v2/data/ias/qa/eu-de-1/linkerd"
  creationTimestamp: null
  labels:
    multicluster.linkerd.io/cluster-name: a2
  name: cluster-credentials-a2
  namespace: linkerd
type: mirror.linkerd.io/remote-kubeconfig
---
